# -*- coding: utf-8 -*-
"""NumPy Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cqpwqd0dZtp0GdQWRgIjOt6QpVtJkgvg
"""

import numpy as np 
import math
#create arrays
arr1d = np.arange(12)
list = [[1,2,3],[6,5,4]]
arr2d = np.array(list)
print(arr1d)
print(arr2d)
#slice
s = arr1d[4:7]
s[1] = 0
print(s)
print(arr1d)
#factorial
fact = np.vectorize(math.factorial)
print(fact(arr2d))